server:
    port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/single-sign-on?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver